### ISSUE TITLE
Github Remote Repositories failing to start Ruff

### ISSUE THREAD

**Issue by Pokeylooted** [astral-sh/ruff-vscode#211] opened 2023-06-15 05:37 UTC
**Issue:** 
Ruff fails to start when using remote repositories.

**Error message:**
```powershell
Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: c:\Users\pokey\AppData\Local\Microsoft\WindowsApps\python3.11.exe c:\Users\pokey\.vscode\extensions\charliermarsh.ruff-2023.20.0-win32-x64\bundled\tool\server.py
Server Command [DEBUG]: c:\Users\pokey\AppData\Local\Microsoft\WindowsApps\python3.11.exe c:\Users\pokey\.vscode\extensions\charliermarsh.ruff-2023.20.0-win32-x64\bundled\tool\_debug_server.py
[Error - 12:29:32 AM] Starting client failed
Launching server using command c:\Users\pokey\AppData\Local\Microsoft\WindowsApps\python3.11.exe failed.
```
**Steps to reproduce:**

1. Install the Github Repositories Extension.
2. Click the blue/green button in the bottom left corner and select “Open remote repository”.
3. Select the desired repository.
4. Upon loading, an error message will appear in the bottom right corner.

**Note:**
The Black Formatter extension also exhibits the same issue.

_Version - v2023.20.0_

**Comment by zanieb** [comment] 2023-06-15 14:40
@Pokeylooted this sounds like an issue with the Github Repositories Extension since it does not work for black either. Have you considered opening an issue at https://github.com/microsoft/vscode-remote-repositories-github?

**Comment by charliermarsh** [comment] 2023-06-15 14:42
\cc @karthiknadig -- do you know if this is expected / unexpected, and whether it affects other extensions based on the template?

**Comment by zanieb** [comment] 2023-06-15 15:06
I can reproduce this as well on macOS. Note as an additional step I had to add the repository's directory to my "trusted" directories.

```
Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: /opt/homebrew/bin/python3 /Users/mz/.vscode/extensions/charliermarsh.ruff-2023.20.0-darwin-arm64/bundled/tool/server.py
Server Command [DEBUG]: /opt/homebrew/bin/python3 /Users/mz/.vscode/extensions/charliermarsh.ruff-2023.20.0-darwin-arm64/bundled/tool/_debug_server.py
[Error - 10:03:42 AM] Starting client failed
Launching server using command /opt/homebrew/bin/python3 failed.
```

isort also failed to load

```
Name: isort
Module: isort
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
[Error - 10:03:42 AM] Starting client failed
Launching server using command /opt/homebrew/bin/python3 failed.
```

**Comment by Pokeylooted** [comment] 2023-06-15 17:40
> @Pokeylooted this sounds like an issue with the Github Repositories Extension since it does not work for black either. Have you considered opening an issue at https://github.com/microsoft/vscode-remote-repositories-github?

https://github.com/microsoft/vscode-remote-repositories-github/issues/341

**Comment by karthiknadig** [comment] 2023-06-16 18:42
I agree with @Pokeylooted this looks like an issue with Github Repositories Extension.

**Comment by charliermarsh** [comment] 2023-06-16 19:59
Closing in favor of the issue in the Remote Repositories extension.

**Closed by charliermarsh** 2023-06-16 19:59 UTC
