### ISSUE TITLE
Ruff: Lint failed (error: Ruff crashed)

### ISSUE THREAD

**Issue by Fissium** [astral-sh/ruff-vscode#362] opened 2023-12-14 11:58 UTC
I just upgraded to the latest version from `v2023.50.0` and got the following error:
```
Ruff: Lint failed (
error: Ruff crashed. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

...quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread 'main' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/str/mod.rs:660:13:
byte index 2 is not a char boundary; it is inside 'Т' (bytes 1..3) of `"Ты`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
)
```

The error is related to these lines of code:
```python
DEFAULT_SYSTEM_PROMPT = (
    "Ты — Сайга, русскоязычный автоматический ассистент. "
    "Ты разговариваешь с людьми и помогаешь им."
)
```

My settings.json
```json
{
    "window.titleBarStyle": "custom",
    "workbench.startupEditor": "none",
    "extensions.autoUpdate": false,
    "explorer.confirmDragAndDrop": false,
    "ruff.importStrategy": "useBundled",
    "editor.fontFamily": "Fira Code",
    "editor.defaultFormatter": "charliermarsh.ruff",
    "editor.fontLigatures": true,
    "files.watcherExclude": {
	    "**/.venv": true
    },
    "files.exclude": {
	    "**/.venv": true
    },
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.diagnosticMode": "openFilesOnly",
    "python.analysis.diagnosticSeverityOverrides": {
	    "reportUnusedImport": "none",
	    "reportUnusedVariable": "none",
	    "reportUndefinedVariable": "none",
	    "reportUnusedClass": "none",
	    "reportUnusedExpression": "none",
	    "reportUnusedFunction": "none",
    },
    "ruff.lint.args": [
	    "--select=ARG",
	    "--select=F",
	    "--select=E",
	    "--select=I001",
    ],
}
```

VS Code extension versions - `v2023.54.0`

Environment:
OS: `Archlinux`
Python: `3.11 (conda env)`

**Comment by charliermarsh** [comment] 2023-12-14 14:02
Thank you!

**Comment by dhruvmanila** [comment] 2023-12-14 14:50
I'm unable to reproduce this on MacOS with the following command:
```
pipx run "ruff==0.1.5" check --select=I,E,F,ARG --no-cache --isolated src/play.py --preview --unsafe-fixes --fix --diff
```

The extension version `v2023.50.0` ships with Ruff `v0.1.5`.

**Comment by charliermarsh** [comment] 2023-12-14 14:52
@dhruvmanila - It looks like they're using latest (they upgraded from `v2023.50.0`).

**Comment by dhruvmanila** [comment] 2023-12-14 14:55
Oh sorry, I misread the first line. Still unable to reproduce with `v0.1.8` :(

**Comment by Fissium** [comment] 2023-12-14 17:29
@dhruvmanila on macOS, I see the following in the logs:
```
OSError: [Errno 86] Bad CPU type in executable: '/Users/fissium/.vscode/extensions/charliermarsh.ruff-2023.54.0-darwin-arm64/bundled/libs/bin/ruff'
```

**Comment by Fissium** [comment] 2023-12-15 07:38
@charliermarsh The original issue has not been resolved. I'm still getting the message `byte index 2 is not a char boundary`

**Comment by Fissium** [comment] 2023-12-15 09:06
If I run `ruff check ./test.ipynb` on a notebook containing
```python
DEFAULT_SYSTEM_PROMPT = (
    "Ты — Сайга, русскоязычный автоматический ассистент. "
    "Ты разговариваешь с людьми и помогаешь им."
)
```
I get the error.
But using a single-line string instead of a multiline one
```python
DEFAULT_SYSTEM_PROMPT = "Ты — Сайга, русскоязычный автоматический ассистент. Ты разговариваешь с людьми и помогаешь им."
```
the error doesn't occur.

**Comment by konstin** [comment] 2023-12-15 09:38
Fixed by https://github.com/astral-sh/ruff/pull/9146

**Closed** 2023-12-15 14:15 UTC
Labels: bug
