### ISSUE TITLE
Is ruff.toml not used?

### ISSUE THREAD

**Issue by daveisfera** [astral-sh/ruff-vscode#327] opened 2023-11-03 19:35 UTC
I just installed Visual Studio Code and this Ruff extension, but it doesn't appear to use the settings from `ruff.toml`. I'd assume that what this extension applies and what running `ruff` on the command line in the same directory would have the same results, but that appears to not be the case, so am I doing something wrong?

**Comment by charliermarsh** [comment] 2023-11-03 20:10
It should be picking up your `ruff.toml` settings in the same way as running from the command line. Can you share a bit more on your project structure, and how you're detecting that your `ruff.toml` _isn't_ being applied?

**Comment by daveisfera** [comment] 2023-11-03 20:16
The primary thing I've noticed is that fixes of imports aren't applied. The formatting change are, but if I move the order of the imports around and save a file, they stay the same and then if I run `ruff` on the command line, they're fixed

**Comment by charliermarsh** [comment] 2023-11-03 20:27
It may be that you need to enable “Organize Imports” or “Fix All” on save. Import sorting is a separate Code Action in VS Code, not part of formatting. 

For example (sorry for lack of formatting, I’m on my phone):

{
  "[python]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  }
}

**Comment by daveisfera** [comment] 2023-11-03 20:28
So it doesn't use the `ruff.toml` directly? Is there a reason that it doesn't? Having the extension and the CLI being exactly the same (i.e. controlled by the config file) seems like the right approach (or at least the behavior that I'd expected)

**Comment by charliermarsh** [comment] 2023-11-03 20:36
It does! But Ruff supports two separate commands: ruff check and ruff format. Those map to different Code Actions in VS Code. If you’re seeing formatting on save, but not import sorting (which is considered part of linting, ie ruff check), I’m just guessing that you may not have the “Fix All” action setup to run on save. Could you share your settings.json?

**Comment by daveisfera** [comment] 2023-11-03 20:54
`Ruff: Fix All` shows as enabled and even when I set it explicitly in `settings.json`, it still doesn't fix the imports (and I tried the same with 

```
{
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "charliermarsh.ruff"
    },
    "files.autoSave": "onWindowChange",
    "ruff.organizeImports": true,
    "ruff.fixAll": true
}
```

**Comment by charliermarsh** [comment] 2023-11-03 21:49
Can you try this instead?

```json
{
  "[python]": {
      "editor.formatOnSave": true,
      "editor.defaultFormatter": "charliermarsh.ruff",
      "editor.codeActionsOnSave": {
        "source.fixAll.ruff": true,
        "source.organizeImports.ruff": true
      }
  },
  "files.autoSave": "onWindowChange",
}
```

**Comment by daveisfera** [comment] 2023-11-03 22:34
Yes, that works. Does that mean the settings in the UI aren't working correctly?

**Comment by dhruvmanila** [comment] 2023-11-06 04:09
What I'm seeing here is that you want to run the organize imports action automatically on save, right @daveisfera? 

If so, then the top level `"ruff.organizeImports": true` will only _enable_ the code action to be visible in the command menu (by default it's true). What Charlie has suggested is to enable running the said code actions automatically on save which is possible with the following lines (omitted irrelevant lines):
```json
      "editor.codeActionsOnSave": {
        "source.organizeImports.ruff": true
      }
```

Hope this answers your query! Feel free to ask any further questions :)

**Comment by dhruvmanila** [comment] 2023-11-06 04:11
(Closing this as resolved, but feel free to ask any further questions :))

**Closed by dhruvmanila** 2023-11-06 04:11 UTC
Labels: question

**Comment by daveisfera** [comment] 2023-11-06 04:28
Isn't there still an issue with the settings in the UI not correctly reflecting the actions that are taken?

**Comment by charliermarsh** [comment] 2023-11-06 04:33
Those settings only control whether Ruff registers as capable of handling those actions _at all_. _When_ those actions run is something that VS Code extensions expect you to configure at a separate level.

As a concrete example... you can have multiple tools and extensions installed that register as capable of handling the `"source.fixAll"` action, which is what runs when you hit "Fix all" in the command palette:

<img width="92" alt="Screen Shot 2023-11-05 at 11 32 21 PM" src="https://github.com/astral-sh/ruff-vscode/assets/1309177/d40684fd-9592-49be-9870-c86e614e18ef">

Notice that both Ruff and ESLint appear there though. Both of those extensions can handle `"source.fixAll"`. (They'd be unlikely to run on the same file, since ESLint is for JavaScript, but you could have multiple Python extensions that support the `"source.fixAll"` action.)

The setting you see in the extension menu just exists to de-register Ruff from acting when you run `"source.fixAll"`.

If you want the `"source.fixAll"` action to run _on-save_, then you do:

```json
"editor.codeActionsOnSave": {
  "source.fixAll": true
}
```

But that's a separate configuration layer than _which extensions act_ when `"source.fixAll"` is triggered.

**Comment by daveisfera** [comment] 2023-11-06 04:50
I'm totally new to Visual Studio Code (trying it out as a long time PyCharm user that's looking for a single IDE that supports Python, Cython and C/C++), so maybe this is normal stuff that I'm not familiar with and I'm still just learning the ropes/proper expectations

But my thought was just that I assumed that installing the extension should "turn it on" or at least the settings in the UI saying it was on should reflect that. Basically, is there not a way to have it turn on by default or have the UI set the settings you asked me to add? Or is manually adding things to `settings.json` just the way that Visual Studio Code works?

**Comment by dhruvmanila** [comment] 2023-11-06 07:20
> But my thought was just that I assumed that installing the extension should "turn it on" or at least the settings in the UI saying it was on should reflect that.

Can you expand on what do you mean when you say "settings in the UI"? The `"ruff.organizeImports": true` is only to register the extension to VSCode of being capable of performing the said action i.e., it says "Hey VSCode, I [Ruff] _can_ organize imports."

Then, one can configure the editor to run the said action on some event like saving a file. So, the registration and running part are separate where the registration part is configured through the extension specific settings (`ruff.organizeImports`) while the running part is configured through the editor specific settings (`editor.codeActionsOnSave`).

> Basically, is there not a way to have it turn on by default or have the UI set the settings you asked me to add? Or is manually adding things to `settings.json` just the way that Visual Studio Code works?

I'm a Neovim user so I'm not sure but I think this is how it works in VS Code :)

**Comment by daveisfera** [comment] 2023-11-07 22:55
> > But my thought was just that I assumed that installing the extension should "turn it on" or at least the settings in the UI saying it was on should reflect that.
> 
> Can you expand on what do you mean when you say "settings in the UI"? The `"ruff.organizeImports": true` is only to register the extension to VSCode of being capable of performing the said action i.e., it says "Hey VSCode, I [Ruff] _can_ organize imports."

If you open `Settings` and then type `Ruff` in the search, there are several check boxes and combo boxes shown, but it appears that most of them are tied to settings other than the ones I had to manually enter to get it to work

For example one of them is this:
```
Ruff: Organize Imports
Whether to register Ruff as capable of handling source.organizeImports actions.
```

> Then, one can configure the editor to run the said action on some event like saving a file. So, the registration and running part are separate where the registration part is configured through the extension specific settings (`ruff.organizeImports`) while the running part is configured through the editor specific settings (`editor.codeActionsOnSave`).

There are settings that are on by default (which are different than what you're mentioning) and they seem to indicate that things are enabled, but they actually aren't

```
Ruff › Code Action: Fix Violation
Whether to display Quick Fix actions to autofix violations.

Ruff: Enable
Whether to enable the Ruff extension.

Ruff: Fix All
Whether to register Ruff as capable of handling source.fixAll actions.
```

**Comment by charliermarsh** [comment] 2023-11-08 00:20
@daveisfera -- I think that perspective is extremely reasonable. The issue is that the fix likely isn't changing the way these options work, but rather, how they're presented to the user and documented. In other words, the settings are actually working as intended, but perhaps the framing to the user is wrong...

Similar to other extensions, like ESLint, we can't really have a setting in the Ruff UI to "enable Optimize Imports on save", since whether that _Code Action_ runs on save is an editor setting, _not_ an extension setting. Instead, the setting you see in the Ruff extension UI controls whether Ruff should run when you open the Command Palette and hit "Organize Imports" (which is a VS Code action, _not_ something defined by the Ruff extension). Like, when that box is checked, if you hit Command + Shift A and select "Organize Imports", Ruff should organize your imports; if the box is unchecked, it shouldn't. Do you agree that that's the behavior you see in practice?

Perhaps there's a better name or description here for the settings.

**Comment by daveisfera** [comment] 2023-11-08 00:52
That makes sense and I agree that's what I'm seeing. I believe a lot of this is from my lack of familiarity with how Visual Studio Code works. I tried some of the things in the readme but couldn't get it to work the way I expected, so maybe a quick start/"here's how to turn it on" for the newbies like me would help out
