### ISSUE TITLE
"ontype" removes required whitespace too aggressively

### ISSUE THREAD

**Issue by spokeydokeys** [astral-sh/ruff-vscode#268] opened 2023-08-21 22:18 UTC
When I installed the extension it was automatically set to "ontype" which caused an issue where I couldn't get even one line of code out.  In the attached video you will see me trying to type `import sys` and you will see ruff remove the space after `import` before I can get `sys` started.  The only way to type a line is to finish it as all one word and then go back and add the whitespace.

Python 3.11
No pyproject.toml settings
settings.json: `"ruff.fixAll": false`
ruff 0.0.285
windows 11, vscode 1.81.1, ruff extension v2023.34.0

https://github.com/astral-sh/ruff-vscode/assets/4625551/43a348d3-e443-4af8-a58b-d5133a85e0ad

**Comment by zanieb** [comment] 2023-08-21 22:32
Hi! Unfortunately, I cannot reproduce this. `onType` controls when Ruff is asked for diagnostics. Ruff should not be applying any fixes unless you perform a code action like "Quick fix". Are there other VSCode settings you are using that may be causing fixes to be applied? I'm also not sure why we'd strip the trailing whitespace.

**Comment by charliermarsh** [comment] 2023-09-04 08:40
Closing for now, happy to revisit if we receive a reproduction.

**Closed by charliermarsh** 2023-09-04 08:40 UTC
Labels: question

**Comment by spokeydokeys** [comment] 2023-09-08 18:04
Thanks for taking a look at this.  I used ruff with the onSave for the last few weeks and today tried the on-type again.  On type now seems to be working as expected, so not sure what was causing the issue 2 weeks ago.
