### ISSUE TITLE
Run for all files in directory without opening them all

### ISSUE THREAD

**Issue by andreypolyak** [astral-sh/ruff-vscode#179] opened 2023-04-28 12:57 UTC
Is it possible to run Ruff for all files in a directory (project) without opening every file? I'd like to quickly see if there are any warnings or errors in a project.

Thanks!

**Comment by charliermarsh** [comment] 2023-04-29 17:45
This might be the same as #145. I'd like to support this!

**Comment by charliermarsh** [comment] 2023-06-17 19:25
(Closing as a duplicate of #145.)

**Closed by charliermarsh** 2023-06-17 19:26 UTC
Labels: question
