### ISSUE TITLE
VS Code setting ruff.interpreter does no longer accept relative paths

### ISSUE THREAD

**Issue by ni-co-la** [astral-sh/ruff-vscode#551] opened 2024-07-23 08:37 UTC
With the latest version of the VS Code extension (v2024.34.0 and v2024.32.0), relative paths for "ruff.interpreter" are no longer accepted (in .vscode/settings.json). 

In our repository, this settings file is shared between for all developers and it points to the venv Python installation inside the repository.
For example: 
```
    "ruff.interpreter": [
        ".venv/bin/python"
    ],
```
This was working just fine in previous versions and is still working fine with other extension like pylint and flake8.

Output:
```
2024-07-23 10:35:41.066 [error] Python version undefined.undefined is not supported.
2024-07-23 10:35:41.066 [error] Selected python path: undefined
2024-07-23 10:35:41.066 [error] Supported versions are 3.7 and above.
```

Setup:
- Windows and Linux
- Python: 3.12
- Ruff: 0.5.4
- VS Code extension: v2024.34.0
- VS Code 1.91.1

**Comment by charliermarsh** [comment] 2024-07-23 13:50
Thanks, will fix!

**Comment by charliermarsh** [comment] 2024-07-23 13:53
I am surprised that `"${workspaceFolder}/.venv/bin/python"` doesn't work.

**Comment by dhruvmanila** [comment] 2024-07-23 14:29
Can you tell me which language server are you using? Are you using the native server or `ruff-lsp` i.e., have you set the `ruff.nativeServer` setting?

I'm asking because there shouldn't be any change if you're using `ruff-lsp`. The meaning of the setting is only changed for the native server where it's only used to find out the `ruff` binary.

If it's the native server then I think it might be related to https://github.com/astral-sh/ruff-vscode/commit/e1777e138865453199626bb51cc6b2842e16360c or https://github.com/astral-sh/ruff-vscode/commit/564a37a0128cf8e55b79e260bb12f74d470eeb0d because earlier we would just pass the interpreter path as `ServerOptions` to create the `LanguageClient` in VS Code, as is still being done for `ruff-lsp`:

https://github.com/astral-sh/ruff-vscode/blob/7896831184d161ca4ab93c93b9db57eaf1609a6c/src/common/server.ts#L210-L263

**Comment by charliermarsh** [comment] 2024-07-23 14:34
We have to expand `settings.interpreter[0]`.

**Comment by ni-co-la** [comment] 2024-07-23 14:34
> I am surprised that "${workspaceFolder}/.venv/bin/python" doesn't work.

Me too. I expected that this should not make a difference for ruff, if I enter the absolute path or if I use the ${workspaceFolder}.

> Can you tell me which language server are you using? Are you using the native server or ruff-lsp i.e., have you set the ruff.nativeServer setting?

`ruff.nativeServer` is not set. 

For the VS Code extension I have the following settings: 
```
    "ruff.importStrategy": "fromEnvironment",
    "ruff.path": [
        "${workspaceFolder}/.venv/bin/ruff"
    ],
    "ruff.lint.args": [
        "--config=${workspaceFolder}/config/ruff.toml"
    ],
    "ruff.format.args": [
        "--config=${workspaceFolder}/config/ruff.toml"
    ],
 ```

**Comment by charliermarsh** [comment] 2024-07-23 14:35
I think I see at least the non-expansion issue.

**Comment by dhruvmanila** [comment] 2024-07-23 14:38
Yeah, I can take it on.

**Comment by charliermarsh** [comment] 2024-07-23 14:39
Thanks. We probably need to expand relative paths too before passing to `execFile`.

**Comment by dhruvmanila** [comment] 2024-07-23 14:46
I think there might be a bigger issue here. We do resolve the variables but only when it's a workspace setting:

https://github.com/astral-sh/ruff-vscode/blob/7896831184d161ca4ab93c93b9db57eaf1609a6c/src/common/settings.ts#L139-L139

And, we don't resolve any variables for the global settings:

https://github.com/astral-sh/ruff-vscode/blob/7896831184d161ca4ab93c93b9db57eaf1609a6c/src/common/settings.ts#L183-L223

Which, I guess, makes sense because it's not tied to any specific workspace.

Black doesn't seem to be resolving the variables from global settings either:

https://github.com/microsoft/vscode-black-formatter/blob/458ed8f03f03c6e021361b7dcf4a8c7ab7c3d5fb/src/common/settings.ts#L149-L171

**Comment by dhruvmanila** [comment] 2024-07-23 14:54
Ok, I can reproduce this, let me check what's actually going on.

**Closed** 2024-07-24 04:35 UTC
Labels: bug

**Comment by dhruvmanila** [comment] 2024-07-24 04:59
Hi @ni-co-la, can you try out the pre-release version which contains the bug fix. You can go to the Ruff extension page and click on "Switch to Pre-Release Version":

<img width="838" alt="Screenshot 2024-07-24 at 10 28 16" src="https://github.com/user-attachments/assets/009a2c42-cecb-48e7-aed6-ff1eee72e9d3">

**Comment by ni-co-la** [comment] 2024-07-24 06:53
I just tested it with the pre-release version and it is working fine with `"ruff.interpreter": [ "${workspaceFolder}/.venv/bin/python" ]`.

 `"ruff.interpreter": [ "./.venv/bin/python" ]` is still not working, which was working in a previous version. 

Which is fine for me, as it is more explicit to use the `${workspaceFolder}`.

**Comment by dhruvmanila** [comment] 2024-07-24 08:30
Thanks for testing it!

> `"ruff.interpreter": [ "./.venv/bin/python" ]` is still not working, which was working in a previous version.

Yes, I explicitly decided not to support this. It wasn't working before either, and you'll probably get the same log messages as in the PR description for earlier versions. It's just that a recent change (https://github.com/astral-sh/ruff-vscode/commit/e665ec7be83b72f7586b30387cd87c8faf62b9e1) made it explicitly visible by removing an unintended fall back mechanism.

I'll make a stable release later today.
