### ISSUE TITLE
Ruff Native server not working In the latest version

### ISSUE THREAD

**Issue by zhengyu-yang** [astral-sh/ruff-vscode#555] opened 2024-07-23 21:21 UTC
Ruff Version:  2024.34.0
VS Code Version:1.91.1 Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729

Ruff Setting:
```
"ruff.nativeServer": true
```

After the latest update, the ruff lsp server will not start. The log looks like:
```
2024-07-23 14:17:50.822 [info] Name: Ruff
2024-07-23 14:17:50.822 [info] Module: ruff
```
All formatting command does not have any response.

**Comment by charliermarsh** [comment] 2024-07-23 21:23
Can you try running `Ruff: Restart server` in VS Code?

**Comment by zhengyu-yang** [comment] 2024-07-23 21:30
The server started after `Ruff: Restart server `. However, when try to format a document, it shows `Ruff does not recognize this file.`  Also, `2024.30.0` works fine.

**Comment by dhruvmanila** [comment] 2024-07-24 02:26
@zhengyu-yang Do you have any other `ruff.*` settings set apart from `ruff.nativeServer` ? Can you provide a screenshot of the VS Code toolbar which is present at the bottom of the window? This mentions the Python version and environment. If possible, can we connect on Discord or another platform? We've been seeing this a lot but unable to reproduce it.

**Comment by dhruvmanila** [comment] 2024-07-24 09:20
@zhengyu-yang Can you try the pre-release version and check if it's still occurring?

<img width="838" alt="Screenshot 2024-07-24 at 10 28 16" src="https://github.com/user-attachments/assets/009a2c42-cecb-48e7-aed6-ff1eee72e9d3">

**Comment by Adam-Antios** [comment] 2024-07-24 09:48
I face the same issue.

**Comment by dhruvmanila** [comment] 2024-07-24 10:30
> I face the same issue.

Can you please provide what issue you're facing along with the details about your setup and settings?

**Comment by Adam-Antios** [comment] 2024-07-24 10:39
My setup is:

Version: 1.92.0-insider
Commit: 22e3447b4b410dcf8426bf70743c5dd4030d6122
Date: 2024-07-23T05:03:52.385Z (1 day ago)

I am facing the exact same issue. Recently Ruff stopped working properly. When I start VS Code, Ruff fails to start and I get the following output:

```
2024-07-24 10:36:48.143 [info] Name: Ruff
2024-07-24 10:36:48.143 [info] Module: ruff
```

In order to get it working I have to either select `Ruff: Restart Server` or change the setting `ruff.nativeServer` from `on` to `auto` or vice versa.

```
    "[python]": {
        "editor.wordWrap": "off",
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.codeActionsOnSave": {
            "source.organizeImports": "explicit",
            // "source.fixAll": "explicit"
        },
        "editor.rulers": [
            {
                "column": 79
            },
        ],
    },
    "python.languageServer": "Jedi",
    "python.analysis.autoImportCompletions": true,
    "python.analysis.completeFunctionParens": true,
    "ruff.nativeServer": "on",
    "ruff.lineLength": 79,
    "ruff.interpreter": [
        "/opt/conda/bin/python",
        "/opt/conda/bin/python3",
    ]
```

**Comment by dhruvmanila** [comment] 2024-07-24 11:54
@Adam-Antios Thank you for the details. I can see that you're using the latest _stable_ version of the extension. Can you try this on the pre-release version? You can do so by clicking on the "Switch to Pre-Release Version" in the VS Code marketplace (image reference: https://github.com/astral-sh/ruff-vscode/issues/555#issuecomment-2247340560)?

**Comment by Adam-Antios** [comment] 2024-07-24 12:02
In the pre-release version Ruff seems to work properly.

**Comment by dhruvmanila** [comment] 2024-07-24 12:10
Thank you for trying it out and confirming. It must've been fixed by #553.

**Comment by zhengyu-yang** [comment] 2024-07-24 15:58
I also tried to switch to pre-release. Interestingly, if I have unsupported settings in `ruff.lint.args`, the native server wont start initially. The extension seems to hang when the notification (`unsupported settings used with the native server. Refer to the logs for more details`) pops up. After I dismiss the notification, the extension start to work.

**Comment by dhruvmanila** [comment] 2024-07-24 19:36
@zhengyu-yang Thanks for trying out the pre-release version and sharing that. That scenario is fixed in #557 and I'm about to release a new version.

**Comment by dhruvmanila** [comment] 2024-07-24 19:52
Hi @zhengyu-yang, @Adam-Antios we just released a new stable version ([`2024.36.0`](https://github.com/astral-sh/ruff-vscode/releases/tag/2024.36.0)) with all the bug fixes. Can you try it out?

**Comment by Adam-Antios** [comment] 2024-07-25 09:49
It seems to work as intended! Thank you for your great work. Since I discovered Ruff I am impressed by its performance and would hate t go back to other alternatives.

**Comment by dhruvmanila** [comment] 2024-07-25 11:03
This looks good! Thank you for confirming. I'll mark this issue as resolved.

**Closed by dhruvmanila** 2024-07-25 11:03 UTC
Labels: needs-mre

**Comment by dhruvmanila** [comment] 2024-07-25 11:05
The issue that the author is facing is also resolved: https://github.com/astral-sh/ruff-vscode/issues/555#issuecomment-2248376029
